### ISSUE TITLE
The Dropbox API v2 does not support mimetypes

### ISSUE THREAD

**Issue by incoming-th** [benjamincrozat/laravel-dropbox-driver#2]
Hi,

Thank you for this provider, I try to add it with elFinder but I get this error message:

![2017-11-18 002318](https://user-images.githubusercontent.com/26375917/32982561-042fac24-ccb9-11e7-8b3c-1d9b29690667.png)

So just asking if you already faced this issue. Sorry if not related to your script, just asking in case anyone know how to fix this.

**Comment by benjamincrozat** [comment]
Hello,

Seems like a change in the API on how Dropbox handles files. I don't know what you're trying to do, but using extensions instead of mimetypes should fix your issue. 

https://www.dropboxforum.com/t5/API-support/no-media-info-for-PNG-files-in-v2-API-list-folder/m-p/216512/highlight/true#M11232

I'm closing the issue since I can't help any more and I'm the only guy who responds here, ha ha. :)

**Comment by incoming-th** [comment]
Hi,

Just in case someone came here with same issue, this can be fixed in the adapter like this:

https://github.com/spatie/flysystem-dropbox/commit/6af2f52fa14406d03031581a2969fb0d94832fb9
